### ISSUE TITLE
Property pane shows blank when trying to select a folder

### ISSUE THREAD

**Issue by soyalejolopez** [GuidoZam/BasicCard-OneDrive-CarouselACE#1]
Hi @GuidoZam, thank you for creating this sample solution. I'm trying to deploy in my test tenant, however, the dropdown for the onedrive folder selection is blank. Thinking maybe it's due to improper Graph permissions. Thoughts on might be the issue? 

![image](https://github.com/GuidoZam/BasicCard-OneDrive-CarouselACE/assets/28953579/de5d5a80-ebb5-4689-a00a-2c711a35b029)

**Comment by soyalejolopez** [comment]
Included "webApiPermissionRequests" requesting permissions for Files.Read.All and Sites.Read.All now able to see the folders in the dropdown. However, the ACE card shows the path to the picture as opposed to rendering the image. Thoughts? 

![image](https://github.com/GuidoZam/BasicCard-OneDrive-CarouselACE/assets/28953579/a52a9228-2dc6-4cf6-8759-d384477daeba)

**Comment by GuidoZam** [comment]
Hi @soyalejolopez thanks for pointing out the issue, this was an "hack" of the correct behavior of the BasicCard, unfortunately I think that this workaround no longer works. I've tried and got the same behavior even with a brand new project 😞 

Maybe you can try using the ImageCard intead of a BasicCard to achieve a similar result.

**Comment by soyalejolopez** [comment]
Hey @GuidoZam , all good. Thank you very much for the reply. I'll give the ImageCard a try 👍 Appreciate you checking, cheers.
